import { useEffect, useState } from "react"
import { FileClock, Loader2 } from "lucide-react"
import { api, type AuditLog } from "@/lib/api"
import { TableColumnMenu } from "@/components/table-column-menu"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export function AuditPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [sortField, setSortField] = useState("created_at"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("desc"); const [filters, setFilters] = useState<Record<string, string>>({})
  const params = new URLSearchParams({ sort_by: sortField, sort_order: sortOrder }); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(`filter_${key}`, value) })
  const queryString = params.toString()
  useEffect(() => { api<{ items: AuditLog[] }>(`/api/audit?${queryString}`).then((result) => setLogs(result.items)).catch(() => undefined).finally(() => setLoading(false)) }, [queryString])
  function setFilter(field: string, value: string) { setFilters((current) => ({ ...current, [field]: value })) }
  const menu = (label: string, field: string) => <TableColumnMenu label={label} field={field} filter={filters[field]} sortField={sortField} sortOrder={sortOrder} onSort={(nextField, order) => { setSortField(nextField); setSortOrder(order) }} onFilter={(value) => setFilter(field, value)} />
  return <Card className="border-border/70 shadow-none"><CardHeader><CardTitle>审计日志</CardTitle><CardDescription>记录用户对系统资源的访问和变更。</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3">{menu("时间", "created_at")}</th><th className="pb-3">{menu("用户", "username")}</th><th className="pb-3">{menu("动作", "action")}</th><th className="pb-3">{menu("资源", "resource")}</th><th className="pb-3">{menu("方法", "method")}</th><th className="pb-3">{menu("路径", "path")}</th><th className="pb-3">{menu("结果", "status_code")}</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="py-12 text-center"><Loader2 className="mx-auto size-5 animate-spin" /></td></tr> : logs.length === 0 ? <tr><td colSpan={7} className="py-12 text-center text-muted-foreground"><FileClock className="mx-auto mb-2 size-5" />暂无审计记录</td></tr> : logs.map((log) => <tr key={log.id} className="border-b last:border-0"><td className="whitespace-nowrap py-4 text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString()}</td><td className="py-4 font-medium">{log.username || "系统"}</td><td className="py-4"><span className="rounded-md bg-muted px-2 py-1 font-mono text-xs">{log.action}</span></td><td className="py-4">{log.resource}</td><td className="py-4 font-mono text-xs">{log.method}</td><td className="py-4 font-mono text-xs text-muted-foreground">{log.path}</td><td className="py-4 text-xs">{log.status_code}</td></tr>)}</tbody></table></div></CardContent></Card>
}
