import { useEffect, useState } from "react"
import { FileClock, Loader2 } from "lucide-react"
import { api, type AuditLog } from "@/lib/api"
import { TableColumnMenu } from "@/components/table-column-menu"
import { TablePagination } from "@/components/table-pagination"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

type Page = { page: number; page_count: number; total: number; page_size: number }
export function AuditPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [sortField, setSortField] = useState("created_at"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("desc"); const [filters, setFilters] = useState<Record<string, string>>({}); const [page, setPage] = useState<Page>({ page: 1, page_count: 1, total: 0, page_size: 20 })
  const params = new URLSearchParams({ sort_by: sortField, sort_order: sortOrder, page: String(page.page), page_size: String(page.page_size) }); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(`filter_${key}`, value) }); const queryString = params.toString()
  useEffect(() => { api<{ items: AuditLog[]; page: Page }>(`/api/audit?${queryString}`).then((result) => { setLogs(result.items); setPage(result.page) }).catch(() => undefined).finally(() => setLoading(false)) }, [queryString])
  function setFilter(field: string, value: string) { setFilters((current) => ({ ...current, [field]: value })); setPage((current) => ({ ...current, page: 1 })) }
  const menu = (label: string, field: string) => <TableColumnMenu label={label} field={field} filter={filters[field]} sortField={sortField} sortOrder={sortOrder} onSort={(nextField, order) => { setSortField(nextField); setSortOrder(order) }} onFilter={(value) => setFilter(field, value)} />
  return <Card className="border-border/70 shadow-none"><CardHeader><CardTitle>业务日志</CardTitle><CardDescription>记录谁在什么时间对什么业务对象做了什么操作，不保存原始 HTTP 访问日志。</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3">{menu("时间", "created_at")}</th><th className="pb-3">{menu("用户", "username")}</th><th className="pb-3">{menu("动作", "action")}</th><th className="pb-3">{menu("对象", "resource")}</th><th className="pb-3">{menu("说明", "detail")}</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="py-12 text-center"><Loader2 className="mx-auto size-5 animate-spin" /></td></tr> : logs.length === 0 ? <tr><td colSpan={5} className="py-12 text-center text-muted-foreground"><FileClock className="mx-auto mb-2 size-5" />暂无业务日志</td></tr> : logs.map((log) => <tr key={log.id} className="border-b last:border-0"><td className="whitespace-nowrap py-4 text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString()}</td><td className="py-4 font-medium">{log.username || "系统"}</td><td className="py-4"><span className="rounded-md bg-muted px-2 py-1 font-mono text-xs">{log.action}</span></td><td className="py-4">{log.resource}</td><td className="py-4 text-muted-foreground">{log.detail}</td></tr>)}</tbody></table></div><TablePagination page={page} onPageChange={(next) => setPage((current) => ({ ...current, page: next }))} /></CardContent></Card>
}
