import { useEffect, useRef, useState } from "react"
import * as Blockly from "blockly"
import { ArrowLeft, Pencil } from "lucide-react"
import { useNavigate, useParams } from "react-router-dom"
import { api, type Dashboard, type DashboardWidget, type PLCVariable } from "@/lib/api"
import { dashboardToolbox, defineDashboardBlocks, loadDashboardDefinition, runDashboardBlocks, setDashboardDataOptions, setDashboardWidgetOptions } from "@/lib/dashboard-blocks"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

function configOf(widget: DashboardWidget) { if (typeof widget.config === "object") return widget.config as Record<string, unknown>; try { return JSON.parse(widget.config) as Record<string, unknown> } catch { return {} } }
function colorOf(value: unknown, fallback: string) { const color = String(value ?? ""); return /^#[0-9a-f]{6}$/i.test(color) ? color : fallback }
export function DashboardViewPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [widgets, setWidgets] = useState<DashboardWidget[]>([]); const [variables, setVariables] = useState<PLCVariable[]>([]); const [error, setError] = useState(""); const hostRef = useRef<HTMLDivElement>(null); const workspaceRef = useRef<Blockly.WorkspaceSvg | null>(null)
  useEffect(() => { api<{ dashboard: Dashboard }>("/api/dashboards/" + id).then((result) => { setDashboard(result.dashboard); setWidgets(result.dashboard.widgets ?? []) }).catch((err) => setError(err instanceof Error ? err.message : "加载看板失败")); api<{ items: PLCVariable[] }>("/api/variables?page_size=100").then((result) => setVariables(result.items)).catch(() => undefined) }, [id])
  useEffect(() => { if (!dashboard || !hostRef.current || workspaceRef.current) return; setDashboardWidgetOptions(widgets.map((item, index) => [`组件 ID: ${item.id ?? "临时-" + (index + 1)} · ${item.widget_type === "text" ? "文字框" : item.widget_type === "image" ? "图片框" : item.widget_type}`, String(item.id ?? index)])); setDashboardDataOptions([], variables.map((variable) => ({ plc_id: variable.plc_id, name: variable.name, data_type: variable.data_type }))); defineDashboardBlocks(); const workspace = Blockly.inject(hostRef.current, { toolbox: dashboardToolbox(), readOnly: true, move: { scrollbars: false, drag: false, wheel: false } }); workspaceRef.current = workspace; loadDashboardDefinition(workspace, dashboard.definition); runDashboardBlocks(workspace, (widgetID, type, value) => { setWidgets((items) => items.map((item, index) => String(item.id ?? index) === widgetID ? { ...item, config: { ...configOf(item), [type === "image" ? "src" : "text"]: value } } : item)) }, (_plcID, variable) => variables.find((item) => item.name === variable)?.current_value ?? ""); return () => { workspace.dispose(); workspaceRef.current = null } }, [dashboard, variables, widgets.length])
  if (!dashboard) return <div className="py-12 text-center">{error || "加载中…"}</div>
  return <div className="space-y-4"><div className="flex items-center justify-between"><Button variant="ghost" onClick={() => navigate("/dashboards")}><ArrowLeft />返回看板列表</Button><Button variant="outline" onClick={() => navigate("/dashboards/" + dashboard.id + "/edit")}><Pencil />编辑看板</Button></div><Card className="overflow-hidden border-border/70 shadow-none"><CardHeader><CardTitle>{dashboard.name}</CardTitle></CardHeader><CardContent className="relative min-h-[760px] p-0" style={{ backgroundColor: colorOf(dashboard.background_color, "#f8fafc") }}>{widgets.map((item, index) => { const config = configOf(item); const imageSource = String(config.src ?? ""); const isText = item.widget_type === "text"; return <div className="absolute overflow-hidden rounded border bg-background/90 p-3 shadow-sm" style={{ left: item.x < 20 ? item.x * 96 + 16 : item.x, top: item.y < 20 ? item.y * 80 + 16 : item.y, width: item.width < 20 ? 192 : item.width, height: item.height < 20 ? 128 : item.height, ...(isText ? { backgroundColor: colorOf(config.background_color, "#ffffff"), color: colorOf(config.text_color, "#0f172a") } : {}) }} key={index}>{isText && <p className="h-full whitespace-pre-wrap break-words text-base">{String(config.text ?? "")}</p>}{item.widget_type === "image" && imageSource && <img className="h-full w-full object-contain" src={imageSource} alt="" />}{item.widget_type === "chart" && <p className="mt-4 text-sm text-muted-foreground">趋势图组件 · 最近 {dashboard.time_range_hours} 小时</p>}</div>})}<div ref={hostRef} className="pointer-events-none absolute left-0 top-0 h-px w-px opacity-0" /></CardContent></Card>{error && <p className="text-sm text-destructive">{error}</p>}</div>
}
