import { useEffect, useRef, useState, type FormEvent } from "react"
import * as Blockly from "blockly"
import * as ZhHans from "blockly/msg/zh-hans"
import { ArrowLeft, Save } from "lucide-react"
import { useNavigate, useParams } from "react-router-dom"
import { api, type FlowFunction, type FlowParameter } from "@/lib/api"
import { defineFunctionBlocks, functionToolbox } from "@/lib/function-blocks"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Form = { code: string; name: string; description: string; return_type: FlowFunction["return_type"]; parameters: string }
const empty: Form = { code: "", name: "", description: "", return_type: "none", parameters: "" }
function parseParameters(value: string): FlowParameter[] { return value.split(",").map((item) => item.trim()).filter(Boolean).map((item) => { const [name, type = "string", options = ""] = item.split(":"); return { name: name.trim(), type: type.trim() as FlowParameter["type"], required: true, options: options ? options.split("|").map((option) => option.trim()).filter(Boolean) : undefined } }) }

export function FunctionEditorPage() {
  const { id = "new" } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState<Form>(empty); const [error, setError] = useState(""); const hostRef = useRef<HTMLDivElement>(null); const workspaceRef = useRef<Blockly.WorkspaceSvg | null>(null)
  useEffect(() => { if (id !== "new") api<{ function: FlowFunction }>("/api/flow-functions/" + id).then((result) => { const parameters = Array.isArray(result.function.parameters) ? result.function.parameters : JSON.parse(result.function.parameters) as FlowParameter[]; setForm({ code: result.function.code, name: result.function.name, description: result.function.description ?? "", return_type: result.function.return_type, parameters: parameters.map((parameter) => parameter.name + ":" + parameter.type + (parameter.options?.length ? ":" + parameter.options.join("|") : "")).join(", ") }); setTimeout(() => { if (workspaceRef.current && result.function.definition) { try { Blockly.serialization.workspaces.load(JSON.parse(result.function.definition) as never, workspaceRef.current) } catch { /* malformed definition */ } } }, 0) }).catch((err) => setError(err instanceof Error ? err.message : "加载函数失败")) }, [id])
  useEffect(() => { if (!hostRef.current || workspaceRef.current) return; defineFunctionBlocks(); Blockly.setLocale(ZhHans as unknown as Record<string, string>); const workspace = Blockly.inject(hostRef.current, { toolbox: functionToolbox(), trashcan: true, grid: { spacing: 24, length: 3, colour: "#c6d4ec", snap: true }, zoom: { controls: true, wheel: true }, move: { scrollbars: true, drag: true, wheel: true } }); workspaceRef.current = workspace; return () => { workspace.dispose(); workspaceRef.current = null } }, [])
  async function save(event: FormEvent) { event.preventDefault(); try { const definition = workspaceRef.current ? Blockly.serialization.workspaces.save(workspaceRef.current) : {}; await api(id === "new" ? "/api/flow-functions" : "/api/flow-functions/" + id, { method: id === "new" ? "POST" : "PUT", body: JSON.stringify({ ...form, parameters: parseParameters(form.parameters), definition }) }); navigate("/flow-functions") } catch (err) { setError(err instanceof Error ? err.message : "保存函数失败") } }
  return <div className="space-y-6"><Button variant="ghost" onClick={() => navigate("/flow-functions")}><ArrowLeft />返回函数列表</Button><form onSubmit={save} className="space-y-6"><Card className="border-border/70 shadow-none"><CardHeader><CardTitle>{id === "new" ? "新建函数积木" : "编辑函数积木"}</CardTitle><CardDescription>先定义函数签名，再在下方 Blockly 编辑器里编排函数内部动作；保存后所有流程都能调用。</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>函数名称</Label><Input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-2"><Label>函数编码</Label><Input placeholder="留空自动生成" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></div><div className="space-y-2"><Label>返回值类型</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.return_type} onChange={(event) => setForm({ ...form, return_type: event.target.value as FlowFunction["return_type"] })}><option value="none">无返回值</option><option value="number">数字</option><option value="string">字符串</option><option value="boolean">布尔值</option></select></div><div className="space-y-2"><Label>参数</Label><Input placeholder="温度:number, 设备:select:炉A|炉B" value={form.parameters} onChange={(event) => setForm({ ...form, parameters: event.target.value })} /></div></div><div className="mt-4 space-y-2"><Label>说明</Label><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}</CardContent></Card><Card className="border-border/70 shadow-none"><CardHeader><CardTitle>函数积木编辑器</CardTitle></CardHeader><CardContent><div ref={hostRef} className="blockly-editor" aria-label="函数 Blockly 编辑器" /></CardContent></Card><Button type="submit"><Save />保存函数</Button></form></div>
}
