import { useEffect, useState, type FormEvent } from "react"
import { ArrowLeft, Save } from "lucide-react"
import { useNavigate, useParams } from "react-router-dom"
import { api, type FlowFunction, type FlowParameter } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Form = { code: string; name: string; description: string; return_type: FlowFunction["return_type"]; parameters: string; definition: string }
const empty: Form = { code: "", name: "", description: "", return_type: "none", parameters: "", definition: "" }
function parseParameters(value: string): FlowParameter[] { return value.split(",").map((item) => item.trim()).filter(Boolean).map((item) => { const [name, type = "string", options = ""] = item.split(":"); return { name: name.trim(), type: type.trim() as FlowParameter["type"], required: true, options: options ? options.split("|").map((option) => option.trim()).filter(Boolean) : undefined } }) }
export function FunctionEditorPage() {
  const { id = "new" } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState<Form>(empty); const [error, setError] = useState("")
  useEffect(() => { if (id !== "new") api<{ function: FlowFunction }>("/api/flow-functions/" + id).then((result) => { const parameters = Array.isArray(result.function.parameters) ? result.function.parameters : JSON.parse(result.function.parameters) as FlowParameter[]; setForm({ code: result.function.code, name: result.function.name, description: result.function.description ?? "", return_type: result.function.return_type, parameters: parameters.map((parameter) => parameter.name + ":" + parameter.type + (parameter.options?.length ? ":" + parameter.options.join("|") : "")).join(", "), definition: result.function.definition ?? "" }) }).catch((err) => setError(err instanceof Error ? err.message : "加载函数失败")) }, [id])
  async function save(event: FormEvent) { event.preventDefault(); try { await api(id === "new" ? "/api/flow-functions" : "/api/flow-functions/" + id, { method: id === "new" ? "POST" : "PUT", body: JSON.stringify({ ...form, parameters: parseParameters(form.parameters), definition: form.definition ? JSON.parse(form.definition) : {} }) }); navigate("/flow-functions") } catch (err) { setError(err instanceof Error ? err.message : "保存函数失败") } }
  return <div className="space-y-6"><Button variant="ghost" onClick={() => navigate("/flow-functions")}><ArrowLeft />返回函数列表</Button><Card className="max-w-4xl border-border/70 shadow-none"><CardHeader><CardTitle>{id === "new" ? "新建流程函数" : "编辑流程函数"}</CardTitle><CardDescription>参数格式：名称:类型[:下拉值1|下拉值2]，例如：温度:number, 设备:select:炉A|炉B。</CardDescription></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>函数名称</Label><Input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-2"><Label>函数编码</Label><Input placeholder="留空自动生成" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></div><div className="space-y-2"><Label>返回值类型</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.return_type} onChange={(event) => setForm({ ...form, return_type: event.target.value as FlowFunction["return_type"] })}><option value="none">无返回值</option><option value="number">数字</option><option value="string">字符串</option><option value="boolean">布尔值</option></select></div><div className="space-y-2"><Label>参数</Label><Input placeholder="温度:number, 设备:select:炉A|炉B" value={form.parameters} onChange={(event) => setForm({ ...form, parameters: event.target.value })} /></div></div><div className="space-y-2"><Label>说明</Label><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div><div className="space-y-2"><Label>函数积木定义（JSON，可选）</Label><Textarea rows={5} placeholder="用于保存函数内部积木或网关映射定义" value={form.definition} onChange={(event) => setForm({ ...form, definition: event.target.value })} /></div>{error && <p className="text-sm text-destructive">{error}</p>}<Button type="submit"><Save />保存函数</Button></form></CardContent></Card></div>
}
