import { useState, type FormEvent } from "react"
import { Loader2, LockKeyhole } from "lucide-react"
import { api, type User } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function LoginPage({ onLogin }: { onLogin: (token: string, user: User) => void }) { const [username, setUsername] = useState("admin"); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const result = await api<{ token: string; user: User }>("/api/auth/login", { method: "POST", body: JSON.stringify({ username, password }) }); onLogin(result.token, result.user) } catch (err) { setError(err instanceof Error ? err.message : "登录失败") } finally { setLoading(false) } }; return <main className="grid min-h-svh place-items-center bg-muted/30 p-6"><Card className="w-full max-w-md border-border/80 shadow-2xl shadow-black/5"><CardHeader className="space-y-4"><div className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground"><LockKeyhole className="size-5" /></div><div><p className="mb-2 text-xs font-medium tracking-[0.24em] text-muted-foreground uppercase">Tsumugi Industry</p><CardTitle className="text-2xl">登录控制台</CardTitle><CardDescription className="mt-2">访问设备、告警与系统权限管理。</CardDescription></div></CardHeader><form onSubmit={submit}><CardContent className="space-y-5"><div className="space-y-2"><Label>账号</Label><Input autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} /></div><div className="space-y-2"><Label>密码</Label><Input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></div>{error && <p className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">{error}</p>}<Button className="w-full" size="lg" disabled={loading}>{loading && <Loader2 className="animate-spin" />}进入系统</Button></CardContent></form></Card></main> }
