import { useEffect, useState } from "react"
import { LineChart, Plus, RefreshCw, Trash2 } from "lucide-react"
import { api, type MonitorItem, type MonitorRecord, type PLC, type PLCVariable } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

type Form = { name: string; plc_id: string; variable_id: string; interval_seconds: string; retention_days: string }
const empty: Form = { name: "", plc_id: "", variable_id: "", interval_seconds: "10", retention_days: "30" }
function chart(records: MonitorRecord[]) {
  const width = 680, height = 180, values = records.map((item) => Number(JSON.parse(item.value) as number)).filter(Number.isFinite)
  if (values.length < 2) return <div className="grid h-44 place-items-center text-sm text-muted-foreground">采样数据不足，点击采样或等待采集</div>
  const min = Math.min(...values), max = Math.max(...values), range = max - min || 1
  const points = values.map((value, index) => (index / (values.length - 1)) * width + "," + (height - ((value - min) / range) * (height - 20) - 10)).join(" ")
  return <svg viewBox={"0 0 " + width + " " + height} className="h-44 w-full"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={points} className="text-primary" /><line x1="0" y1={height - 10} x2={width} y2={height - 10} stroke="currentColor" className="text-border" /></svg>
}
export function MonitoringPage() {
  const [items, setItems] = useState<MonitorItem[]>([]); const [plcs, setPlcs] = useState<PLC[]>([]); const [variables, setVariables] = useState<PLCVariable[]>([]); const [records, setRecords] = useState<Record<number, MonitorRecord[]>>({}); const [form, setForm] = useState<Form>(empty); const [open, setOpen] = useState(false); const [error, setError] = useState("")
  async function load() { try { const result = await api<{ items: MonitorItem[] }>("/api/monitor-items"); setItems(result.items); const charts = await Promise.all(result.items.map(async (item) => [item.id, (await api<{ items: MonitorRecord[] }>("/api/monitor-items/" + item.id + "/records?hours=24")).items] as const)); setRecords(Object.fromEntries(charts)) } catch (err) { setError(err instanceof Error ? err.message : "加载监控项失败") } }
  useEffect(() => { void load(); api<{ items: PLC[] }>("/api/plcs?page_size=100").then((result) => setPlcs(result.items)).catch(() => undefined); api<{ items: PLCVariable[] }>("/api/variables?page_size=100").then((result) => setVariables(result.items)).catch(() => undefined) }, [])
  const availableVariables = variables.filter((item) => String(item.plc_id) === form.plc_id)
  async function create() { try { await api("/api/monitor-items", { method: "POST", body: JSON.stringify({ ...form, plc_id: Number(form.plc_id), variable_id: Number(form.variable_id), interval_seconds: Number(form.interval_seconds), retention_days: Number(form.retention_days) }) }); setOpen(false); setForm(empty); await load() } catch (err) { setError(err instanceof Error ? err.message : "创建监控项失败") } }
  async function sample(item: MonitorItem) { try { await api("/api/monitor-items/" + item.id + "/sample", { method: "POST", body: "{}" }); await load() } catch (err) { setError(err instanceof Error ? err.message : "采样失败") } }
  async function remove(item: MonitorItem) { await api("/api/monitor-items/" + item.id, { method: "DELETE" }); await load() }
  return <div className="space-y-6"><Card className="border-border/70 shadow-none"><CardHeader><div className="flex items-center justify-between"><div><CardTitle>PLC 监控项</CardTitle><CardDescription>选择 PLC 和变量，按间隔采样并保存历史数据；图表范围为最近 24 小时。</CardDescription></div><Button onClick={() => setOpen(true)}><Plus />新建监控项</Button></div></CardHeader><CardContent className="space-y-4">{items.map((item) => <div className="rounded-xl border p-4" key={item.id}><div className="mb-2 flex items-start justify-between"><div><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.plc?.name} · {item.variable?.name} · 每 {item.interval_seconds} 秒 · 保留 {item.retention_days} 天</p></div><div className="flex gap-1"><Button variant="ghost" size="icon-sm" title="立即采样" onClick={() => void sample(item)}><RefreshCw /></Button><Button variant="ghost" size="icon-sm" title="删除" onClick={() => void remove(item)}><Trash2 /></Button></div></div>{chart(records[item.id] ?? [])}<div className="flex items-center gap-2 text-xs text-muted-foreground"><LineChart className="size-3" />{records[item.id]?.length ?? 0} 个采样点 · {item.last_sampled_at ? new Date(item.last_sampled_at).toLocaleString() : "尚未采样"}</div></div>)}{items.length === 0 && <div className="py-12 text-center text-muted-foreground">暂无监控项</div>}{error && <p className="text-sm text-destructive">{error}</p>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>新建监控项</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>名称</Label><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-2"><Label>PLC</Label><Select value={form.plc_id} onValueChange={(plc_id) => setForm({ ...form, plc_id, variable_id: "" })}><SelectTrigger><SelectValue placeholder="选择 PLC" /></SelectTrigger><SelectContent>{plcs.map((plc) => <SelectItem value={String(plc.id)} key={plc.id}>{plc.name} · {plc.code}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>变量</Label><Select value={form.variable_id} onValueChange={(variable_id) => setForm({ ...form, variable_id })}><SelectTrigger><SelectValue placeholder="选择变量" /></SelectTrigger><SelectContent>{availableVariables.map((variable) => <SelectItem value={String(variable.id)} key={variable.id}>{variable.name} · {variable.data_type}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>采集间隔（秒）</Label><Input type="number" min="1" value={form.interval_seconds} onChange={(event) => setForm({ ...form, interval_seconds: event.target.value })} /></div><div className="space-y-2"><Label>保留时长（天）</Label><Input type="number" min="1" value={form.retention_days} onChange={(event) => setForm({ ...form, retention_days: event.target.value })} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>取消</Button><Button disabled={!form.name || !form.plc_id || !form.variable_id} onClick={() => void create()}>创建</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
