import { useEffect, useState, type FormEvent } from "react"
import { Database, Pencil } from "lucide-react"
import { api, type Setting } from "@/lib/api"
import { TableColumnMenu } from "@/components/table-column-menu"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function SettingsPage() {
  const [settings, setSettings] = useState<Setting[]>([]); const [editing, setEditing] = useState<Setting | null>(null); const [value, setValue] = useState(""); const [sortField, setSortField] = useState("key"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc"); const [filters, setFilters] = useState<Record<string, string>>({}); const [error, setError] = useState("")
  const params = new URLSearchParams({ sort_by: sortField, sort_order: sortOrder }); Object.entries(filters).forEach(([key, filter]) => { if (filter) params.set(`filter_${key}`, filter) }); const queryString = params.toString()
  useEffect(() => { api<{ items: Setting[] }>(`/api/settings?${queryString}`).then((result) => setSettings(result.items)).catch((err) => setError(err instanceof Error ? err.message : "加载设置失败")) }, [queryString])
  function setFilter(field: string, filter: string) { setFilters((current) => ({ ...current, [field]: filter })) }
  async function save(event: FormEvent) { event.preventDefault(); if (!editing) return; try { await api(`/api/settings/${encodeURIComponent(editing.key)}`, { method: "PUT", body: JSON.stringify({ value }) }); setSettings((current) => current.map((setting) => setting.key === editing.key ? { ...setting, value } : setting)); setEditing(null) } catch (err) { setError(err instanceof Error ? err.message : "保存设置失败") } }
  return <div className="space-y-6"><Card className="border-border/70 shadow-none"><CardHeader><CardTitle>运行设置</CardTitle><CardDescription>应用设置存储在数据库中，环境变量仅负责启动连接。</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3"><TableColumnMenu label="设置项" field="key" filter={filters.key} sortField={sortField} sortOrder={sortOrder} onSort={(field, order) => { setSortField(field); setSortOrder(order) }} onFilter={(filter) => setFilter("key", filter)} /></th><th className="pb-3"><TableColumnMenu label="值" field="value" filter={filters.value} sortField={sortField} sortOrder={sortOrder} onSort={(field, order) => { setSortField(field); setSortOrder(order) }} onFilter={(filter) => setFilter("value", filter)} /></th><th className="pb-3 text-right font-medium">操作</th></tr></thead><tbody>{settings.map((setting) => <tr key={setting.key} className="border-b last:border-0"><td className="py-4 font-mono text-xs text-muted-foreground">{setting.key}</td><td className="py-4">{setting.value}</td><td className="py-4 text-right"><Button variant="ghost" size="icon-sm" onClick={() => { setEditing(setting); setValue(setting.value) }}><Pencil /></Button></td></tr>)}</tbody></table></div>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</CardContent></Card><Card className="border-border/70 shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><Database className="size-4" />设置说明</CardTitle><CardDescription>连接信息仍由环境变量提供，业务设置在这里维护。</CardDescription></CardHeader></Card><Dialog open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>编辑系统设置</DialogTitle><DialogDescription>{editing?.key}</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><div className="space-y-2"><Label>值</Label><Input value={value} onChange={(event) => setValue(event.target.value)} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditing(null)}>取消</Button><Button type="submit">保存</Button></DialogFooter></form></DialogContent></Dialog></div>
}
