import { useState, type FormEvent } from "react"
import { Loader2, CircleGauge } from "lucide-react"
import { api } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

export function SetupPage({ onComplete }: { onComplete: () => void }) { const [form, setForm] = useState({ system_name: "Tsumugi Industry", username: "admin", password: "", timezone: "Asia/Shanghai" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { await api("/api/setup", { method: "POST", body: JSON.stringify(form) }); onComplete() } catch (err) { setError(err instanceof Error ? err.message : "初始化失败") } finally { setLoading(false) } }; return <main className="grid min-h-svh place-items-center bg-muted/30 p-6"><Card className="w-full max-w-lg border-border/80 shadow-2xl shadow-black/5"><CardHeader className="space-y-4"><div className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground"><CircleGauge className="size-5" /></div><div><p className="mb-2 text-xs font-medium tracking-[0.24em] text-muted-foreground uppercase">Tsumugi Industry / Setup</p><CardTitle className="text-2xl">初始化控制台</CardTitle><CardDescription className="mt-2">创建第一位系统管理员，并保存系统级设置。</CardDescription></div></CardHeader><form onSubmit={submit}><CardContent className="space-y-5"><div className="space-y-2"><Label>系统名称</Label><Input value={form.system_name} onChange={(e) => setForm({ ...form, system_name: e.target.value })} /></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label>管理员账号</Label><Input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></div><div className="space-y-2"><Label>管理员密码</Label><Input type="password" minLength={8} placeholder="至少 8 位" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div></div><div className="space-y-2"><Label>系统时区</Label><Select value={form.timezone} onValueChange={(timezone) => setForm({ ...form, timezone })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Asia/Shanghai">Asia/Shanghai</SelectItem><SelectItem value="UTC">UTC</SelectItem><SelectItem value="Asia/Tokyo">Asia/Tokyo</SelectItem></SelectContent></Select><p className="text-xs text-muted-foreground">时区等运行设置会写入数据库。</p></div>{error && <p className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">{error}</p>}<Button className="w-full" size="lg" disabled={loading}>{loading && <Loader2 className="animate-spin" />}完成初始化</Button></CardContent></form></Card></main> }
