import { useCallback, useEffect, useState, type FormEvent } from "react"
import { Eye, Loader2, Play, Plus, Send, Trash2, XCircle } from "lucide-react"
import { api, type FlowDefinition, type WorkOrder } from "@/lib/api"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

type Page = { page: number; page_count: number; total: number; page_size: number }
type FormState = { name: string; flow_definition_id: string; flow_variables: Record<string, string> }
const emptyForm: FormState = { name: "", flow_definition_id: "", flow_variables: {} }
const statusLabels: Record<WorkOrder["status"], string> = { draft: "草稿", released: "已下达", running: "运行中", paused: "已暂停", completed: "已完成", cancelled: "已取消" }
function statusBadge(status: WorkOrder["status"]) { return <Badge variant={status === "cancelled" ? "destructive" : status === "completed" ? "secondary" : status === "running" ? "default" : "outline"}>{statusLabels[status]}</Badge> }
function flowVariables(flow?: FlowDefinition) { if (!flow) return []; try { return (JSON.parse(flow.definition) as { variables?: { name: string; type: string; default_value?: string }[] }).variables ?? [] } catch { return [] } }
function flowOptions(flow?: FlowDefinition) { if (!flow) return []; try { return (JSON.parse(flow.definition) as { options?: string[] }).options ?? [] } catch { return [] } }

export function WorkOrdersPage() {
  const [orders, setOrders] = useState<WorkOrder[]>([]); const [flows, setFlows] = useState<FlowDefinition[]>([]); const [page, setPage] = useState<Page>({ page: 1, page_count: 1, total: 0, page_size: 20 }); const [open, setOpen] = useState(false); const [detail, setDetail] = useState<WorkOrder | null>(null); const [form, setForm] = useState<FormState>(emptyForm); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const result = await api<{ items: WorkOrder[]; page: Page }>("/api/work-orders?page_size=100&sort_order=desc"); setOrders(result.items); setPage(result.page) } catch (err) { setError(err instanceof Error ? err.message : "加载工单失败") } }, [])
  useEffect(() => { void load(); api<{ items: FlowDefinition[] }>("/api/flows?page_size=100&filter_status=published").then((result) => setFlows(result.items)).catch(() => undefined) }, [load])
  const selectedFlow = flows.find((flow) => String(flow.id) === form.flow_definition_id); const variables = flowVariables(selectedFlow); const options = flowOptions(selectedFlow)
  function create() { setForm(emptyForm); setError(""); setOpen(true) }
  function changeFlow(id: string) { const flow = flows.find((item) => String(item.id) === id); const values = Object.fromEntries(flowVariables(flow).map((item) => [item.name, item.default_value ?? ""])); setForm({ ...form, flow_definition_id: id, flow_variables: values }) }
  async function save(event: FormEvent) { event.preventDefault(); if (!selectedFlow) return; setSaving(true); setError(""); try { await api("/api/work-orders", { method: "POST", body: JSON.stringify({ name: form.name, flow_definition_id: Number(form.flow_definition_id), flow_variables: form.flow_variables }) }); setOpen(false); await load() } catch (err) { setError(err instanceof Error ? err.message : "创建工单失败") } finally { setSaving(false) } }
  async function action(order: WorkOrder, name: string) { try { await api(`/api/work-orders/${order.id}/${name}`, { method: "POST", body: "{}" }); await load() } catch (err) { setError(err instanceof Error ? err.message : "工单操作失败") } }
  async function remove(order: WorkOrder) { try { await api(`/api/work-orders/${order.id}`, { method: "DELETE" }); await load() } catch (err) { setError(err instanceof Error ? err.message : "删除工单失败") } }
  return <div className="space-y-6"><Card className="border-border/70 shadow-none"><CardHeader><div className="flex items-center justify-between gap-4"><div><CardTitle>生产工单</CardTitle><CardDescription>新建工单只需填写名称、选择已发布流程，以及填写流程变量。</CardDescription></div><Button onClick={create}><Plus />新建工单</Button></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="pb-3">名称</th><th className="pb-3">流程</th><th className="pb-3">变量</th><th className="pb-3">状态</th><th className="pb-3 text-right">操作</th></tr></thead><tbody>{orders.map((order) => <tr className="border-b last:border-0" key={order.id}><td className="py-4">{order.product_name || order.name || order.code}<div className="font-mono text-xs text-muted-foreground">{order.code}</div></td><td className="py-4">{order.flow_definition?.name ?? "传统工单"}</td><td className="py-4 text-xs text-muted-foreground">{order.flow_variables ? Object.keys(JSON.parse(order.flow_variables) as Record<string, unknown>).length : 0} 项</td><td className="py-4">{statusBadge(order.status)}</td><td className="py-4 text-right"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon-sm" title="查看" onClick={() => api<{ work_order: WorkOrder }>(`/api/work-orders/${order.id}`).then((result) => setDetail(result.work_order))}><Eye /></Button>{order.status === "draft" && <><Button variant="ghost" size="icon-sm" title="下达" onClick={() => void action(order, "release")}><Send /></Button><Button variant="ghost" size="icon-sm" title="删除" onClick={() => void remove(order)}><Trash2 /></Button></>}{order.status === "released" && <Button variant="ghost" size="icon-sm" title="启动" onClick={() => void action(order, "start")}><Play /></Button>}{order.status === "running" && <Button variant="ghost" size="icon-sm" title="暂停" onClick={() => void action(order, "pause")}><XCircle /></Button>}</div></td></tr>)}{orders.length === 0 && <tr><td colSpan={5} className="py-12 text-center text-muted-foreground">暂无工单</td></tr>}</tbody></table></div><div className="mt-4 text-xs text-muted-foreground">共 {page.total} 条</div></CardContent></Card>{error && <p className="text-sm text-destructive">{error}</p>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>新建生产工单</DialogTitle><DialogDescription>流程定义中的变量会自动生成填写项。</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><div className="space-y-2"><Label>工单名称</Label><Input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="例如：A产品 08-24 批次" /></div><div className="space-y-2"><Label>选择流程</Label><Select value={form.flow_definition_id} onValueChange={changeFlow}><SelectTrigger><SelectValue placeholder="选择已发布流程" /></SelectTrigger><SelectContent>{flows.map((flow) => <SelectItem value={String(flow.id)} key={flow.id}>{flow.name} · v{flow.version}</SelectItem>)}</SelectContent></Select></div>{variables.length > 0 && <div className="space-y-3 rounded-lg border p-3"><p className="text-sm font-medium">流程变量</p>{variables.map((variable) => <div className="space-y-1" key={variable.name}><Label>{variable.name} <span className="text-xs text-muted-foreground">({variable.type})</span></Label>{variable.type === "option" ? <Select value={form.flow_variables[variable.name] ?? ""} onValueChange={(value) => setForm({ ...form, flow_variables: { ...form.flow_variables, [variable.name]: value } })}><SelectTrigger><SelectValue placeholder="选择流程下拉项" /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select> : <Input required={variable.type !== "boolean"} type={variable.type === "number" ? "number" : "text"} value={form.flow_variables[variable.name] ?? ""} onChange={(event) => setForm({ ...form, flow_variables: { ...form.flow_variables, [variable.name]: event.target.value } })} />}</div>)}</div>}{variables.length === 0 && selectedFlow && <p className="rounded-lg bg-muted p-3 text-sm text-muted-foreground">该流程未定义变量，可直接创建工单。</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={saving || !selectedFlow}>{saving && <Loader2 className="animate-spin" />}创建工单</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(detail)} onOpenChange={(next) => !next && setDetail(null)}><DialogContent><DialogHeader><DialogTitle>{detail?.product_name || detail?.code}</DialogTitle><DialogDescription>{detail && statusLabels[detail.status]} · {detail?.flow_definition?.name ?? "传统工单"}</DialogDescription></DialogHeader>{detail && <div className="space-y-2 text-sm">{detail.flow_variables && Object.entries(JSON.parse(detail.flow_variables) as Record<string, unknown>).map(([key, value]) => <div className="flex justify-between border-b py-2" key={key}><span>{key}</span><span>{String(value)}</span></div>)}<p className="pt-2 text-xs text-muted-foreground">工序数量：{detail.steps?.length ?? 0}</p></div>}<DialogFooter><Button variant="outline" onClick={() => setDetail(null)}>关闭</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
